### ISSUE TITLE
Make CPM classes/packages/routines be system-wide mapped

### ISSUE THREAD

**Issue by tsafin** [cpmteam/CPM#30]
Looks like we need %ALL namespace mapping involved

**Comment by daimor** [comment]
Just need an %Installer class

**Comment by tsafin** [comment]
Yeah, looks like:
- we could stay with current names for classes/routines/globals;
- if we add mappings for them (CPM.*) to %ALL;
- once we have %Installer working.

**Comment by tsafin** [comment]
And the last thing I want is to rename everything. If we could live witth current names but still be system-wide - so be it.

**Comment by tsafin** [comment]
This is half-way done in tsafin-devel branch via automatic projection massaging:
- there is established CPM.*, %CPM.* mapping to %ALL for globals, routines, packages;
- but CPM.* classes content is not yet visible system-wide.

Thus I'm temporarily switching to CPM namespace for CPM.Registry.Package content, proceed operations and return back.

This hack is acceptible at the time of initial population of remote repository, but is inacceptible even for alpha. Need to figure out what is missing for CPM.Registtry.Package mapping.

**Comment by tsafin** [comment]
Although, OTOH, for alpha, without global packages installation, and all local installs, we are probably ok to have no sharing of CPM.Registry.Package at all. i.e.
```
CPM>install component
```
should install it locally to the current namespace, and we are ok with that.

We should probably remove switch to CPM namespace upon shell invocation.

**Comment by tsafin** [comment]
Closed by #39
