### ISSUE TITLE
CPM web package description from readme 

### ISSUE THREAD

**Issue by daimor** [cpmteam/CPM#35]
Page with detailed information for a package, should show content from readme.md as it did on npmjs.com

**Comment by tsafin** [comment]
It's still work in progress, but here how it will look like once we have server-side work done (at the moment we have only part of client-side logics there)

http://intersystems-ru.github.io/CPM/#/repo/webterminal?local=1

**Comment by daimor** [comment]
Anyway it looks good. I think that client-side will be enough, because readme on github repo, could go away from released version in CPM repo. And could contain incompatible information.

**Comment by tsafin** [comment]
If package was properly populated then its' .readmeText is visualized. See http://cpmteam.github.io/#!/repo/intersystems-ru-webterminal
